# Generated by Django 5.2.3 on 2025-06-25 17:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم البدل')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'شهري'), ('ANNUAL', 'سنوي'), ('ONE_TIME', 'مرة واحدة')], max_length=20, verbose_name='تكرار البدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع البدل',
                'verbose_name_plural': 'أنواع البدلات',
                'ordering': ['name_arabic'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('hire_date', models.DateField(verbose_name='تاريخ التوظيف')),
                ('id_number', models.CharField(max_length=50, verbose_name='رقم الهوية/الإقامة')),
                ('category', models.CharField(choices=[('LABOR', 'عمالة'), ('STAFF', 'موظفين'), ('MANAGER', 'إداري'), ('ENGINEER', 'مهندس'), ('TECHNICIAN', 'فني')], max_length=20, verbose_name='الفئة')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='آخر راتب أساسي')),
                ('insurance_type', models.CharField(choices=[('BASIC', 'أساسي'), ('COMPREHENSIVE', 'شامل'), ('PREMIUM', 'ممتاز')], max_length=20, verbose_name='نوع التأمين الطبي')),
                ('num_wives', models.PositiveIntegerField(default=0, verbose_name='عدد الزوجات')),
                ('num_children', models.PositiveIntegerField(default=0, verbose_name='عدد الأبناء')),
                ('recruitment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الاستقدام')),
                ('training_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة التدريب')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('type', models.CharField(choices=[('CASH', 'نقدي'), ('IN_KIND', 'عيني')], default='CASH', max_length=10, verbose_name='طبيعة البدل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.allowancetype', verbose_name='نوع البدل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بدل',
                'verbose_name_plural': 'البدلات',
                'unique_together': {('employee', 'allowance_type')},
            },
        ),
    ]
