# Generated by Django 5.2.3 on 2025-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_ticket_and_training_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='insurance_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20, verbose_name='نوع التأمين الطبي'),
        ),
    ]
